# Generated by Django 4.2.3 on 2023-07-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('internal_marks', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCA_firstyear_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MCA_secondyear_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MCA_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MSc_firstyear_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MSc_secondyear_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MSc_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('cpassword', models.CharField(max_length=250)),
                ('is_saved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.course')),
                ('students', models.ManyToManyField(related_name='subjects', to='ccsit_internal_mark_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('cpassword', models.CharField(max_length=250)),
                ('is_saved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.course')),
                ('students', models.ManyToManyField(related_name='subject_allotments', to='ccsit_internal_mark_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allotments', to='ccsit_internal_mark_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.electivecourse')),
                ('elective_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.electivesubject')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('assignment', models.IntegerField()),
                ('seminar', models.IntegerField()),
                ('test1', models.IntegerField()),
                ('test2', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('marks_saved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveSubjectAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_subjects', models.ManyToManyField(to='ccsit_internal_mark_app.electivesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='electivecourse',
            name='elective_subjects',
            field=models.ManyToManyField(to='ccsit_internal_mark_app.electivesubject'),
        ),
    ]
