# Generated by Django 4.2.3 on 2023-07-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('marks_saved', models.BooleanField(default=False)),
                ('elective_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.electivesubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.student')),
            ],
        ),
    ]
