# Generated by Django 4.2.3 on 2023-07-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0002_electivemarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectiveMarks',
        ),
    ]
