# Generated by Django 4.2.3 on 2023-07-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0004_electivemarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electivemarks',
            old_name='elective_marks',
            new_name='assignment',
        ),
        migrations.RemoveField(
            model_name='electivemarks',
            name='marks_saved',
        ),
        migrations.AddField(
            model_name='electivemarks',
            name='attendance',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electivemarks',
            name='seminar',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electivemarks',
            name='test1',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electivemarks',
            name='test2',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electivemarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.studentregistration'),
        ),
    ]
