# Generated by Django 4.2.3 on 2023-07-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0007_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Student_Login',
        ),
    ]
