# Generated by Django 4.2.3 on 2023-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0009_delete_student_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
