# Generated by Django 4.2.3 on 2023-07-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0010_student_reset_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reset_password_token',
        ),
    ]
