# Generated by Django 4.2.3 on 2023-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0011_remove_student_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
