# Generated by Django 4.2.3 on 2023-08-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0014_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
