# Generated by Django 4.2.3 on 2023-08-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0018_electivemarks_elective_marks_saved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electivemarks',
            old_name='total_marks',
            new_name='total_elective_marks',
        ),
    ]
