# Generated by Django 4.2.3 on 2023-08-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0019_rename_total_marks_electivemarks_total_elective_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.student'),
        ),
    ]
