# Generated by Django 4.2.3 on 2023-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0020_alter_studentregistration_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='name',
            new_name='username',
        ),
    ]
