# Generated by Django 4.2.3 on 2023-08-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0021_rename_name_studentregistration_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='username',
            new_name='name',
        ),
    ]
