# Generated by Django 4.2.3 on 2023-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0022_rename_username_studentregistration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='username',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
