# Generated by Django 4.2.3 on 2023-08-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0023_remove_studentregistration_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='name',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.student'),
            preserve_default=False,
        ),
    ]
