# Generated by Django 4.2.3 on 2023-08-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0024_remove_studentregistration_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='name',
            new_name='username',
        ),
    ]
