# Generated by Django 4.2.3 on 2023-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0025_rename_name_studentregistration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
