# Generated by Django 4.2.3 on 2023-08-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0028_rename_elective_subject_studentregistration_elective_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='elective_subjects',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='elective_subjects',
            field=models.ManyToManyField(to='ccsit_internal_mark_app.electivesubject'),
        ),
    ]
