# Generated by Django 4.2.3 on 2023-08-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0029_remove_studentregistration_elective_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='elective_subjects',
            new_name='elective_subject',
        ),
    ]
