# Generated by Django 4.2.3 on 2023-08-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0031_electivemarks_elective_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electivemarks',
            name='elective_course',
        ),
    ]
