# Generated by Django 4.2.3 on 2023-08-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0032_remove_electivemarks_elective_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivemarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccsit_internal_mark_app.studentregistration', unique=True),
        ),
    ]
