# Generated by Django 4.2.3 on 2023-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsit_internal_mark_app', '0033_alter_electivemarks_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
